general:
  environment: Production
  serverPort: 3000
  clientUrl: http://localhost:8080
  serviceToken: abcd
  secret: ab012345678901234567890123456789


database:
  host: mongo
  databaseName: dsw-server-test
  port: 27017
  authEnabled: false
  username:
  password:

messaging:
  enabled: true
  username: admin
  password: password

mail:
  enabled: false
  name:
  email:
  host:
  port:
  ssl:
  username:
  password:
