general:
  environment: Production
  serverPort: 3000
  clientUrl: http://localhost:8080
  secret: ab012345678901234567890123456789
  rsaPrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKQIBAAKCAgEAxzFes2sALeBv2HOHRwS2smXwSjsHB0P37gi9RXM81siGz0og
    /7PE5TNgaO4gRaeiPFGLaoh+zsku+vcdtRh4f0At8mvCMcSejW9QiyJGjIeJs/di
    N4Uf4r2vayYPKDEFAPrzAZZ9b9jvvxn1Q6zmtnPwwzTUGwfJj3mCNbo+5K/PhVyZ
    +90nkXSjiLsvg3dICBUGcDVYnupddZj6N4Uap9iQh4bGgz8OyqmW/JrXoYFzf1zi
    gocHLgzY0itypiCdwASQFbJNkg9WpV4cZ+NZnLm3PFE65w1QkH4/AF4ZY6+tLRUf
    4/Lxwr6ljzlCdfTY/VmycxvWgei9Xshn/8ho+Zcv6Qd+/+itRRUdNWj5tDSwPgMj
    rnlMREh8ZrzsrzDKKiYwV9twRaggPCpvLjldkpd2wj3VUzTvSowR8GYDKdJOsox6
    k+WE/aA7ktQw5JQ/B24R1Us7yroPGPn98UvbxpIHRXdH+SY5/8c4syi9TzgP00Vx
    Xow6KSIBEGMki7LoxjAHG2rHphXE3LlcfPTMOy1K+lAfH7FZYtDpmQTsngUXFsis
    ZDGHTVXy74fnvvy/JLk9C4oKCnTqsUVsBLu3/bO0Zty5omfxEMbvKnQWzIAKO0aS
    ZJKH4TSRGJMoLqDR1wZJ2NI9C3cjDy2yOU7hFb8pK2aDW+MlXHHIY8OJJT8CAwEA
    AQKCAgEAg3ESmrZq4dsOMvjZNYXowQP/chxNYP/65Lojm2aVqO2d979k0xbfQJeM
    cPFhnlUl+0OcCeqUMwQS2kyi79N8AAxrxWJSPOEP9yiTL5yojScLORRvXU+dYNPm
    o3/z1IO0V5dBL7UMhPfUDHimncfEXnVXVJjRthyHZwO5ZpbF1cYl3Ezk14xyBcu/
    9gP/MHNPtvWY0AaDuinRDj6qLmTI2CVSCfxnlkfQDO+n0Hyk+dAgVNUIKzXLCRo1
    IUrGVtWDAyh/o7GK+mzgsjLN78fYZFEwlr7LbZgdp5uHG0j83Aka73rXFmZEHkwL
    l90i/A9b+KJt3QNro0HfZGI+Lk0i5xU/1F85RNlEnMe7k1as4J9qx4wpfPXCFFRH
    GIZqqPdG9fktKFa57NVBAXscD5238CxL2zIDpUZTlNiqTzGd6OuEHuJx5uWeamoR
    WYeoKvLq8L0cS6Vqln24EA3TEFiKLxCVnPKEtRcYTYUMc0wpiElA6zJXxX6jfJRy
    g5D1A2HzU4YLynHIm7S8w4CWx0ICdf506zbXr7ZZn/E+VxwsfeZphI5YLnR7jMa3
    tFFdLYnP4sUt6R5ftAMcqAu4BF+8vloVU1vnStru1yssdWNNTCYacx8gsA/PyA9C
    4NLqB/OHC2wfqKAudTTqBxmz1JZsH+CO90Yc4JLEmC+E5p1MB5ECggEBAPXiVAI/
    jpFfzO7ljFnsegi3JeYV7eJfnOn/AYGBCU/O6tVxlRp7nY7ljpFGB/A2gqYYC6+T
    IakX+EKIiQt0Uq9iIBulPrKGE0GeUi06QNQZlePFNz8LToZANH91nd6F56ss5xnN
    kKvvpOlsNckx2/hbdxrvqomoda860G6xADQfsL6fIi52Dslf9boni/kDVL4sj6EM
    WIG/BwtC788Se4oYgo5gSI46gvmVyyHG2JBwlEjlYoDf3KGecp6P9d7hMPoNNHwd
    xR4NGhBkgdjC5ROdzWYjFsE2qbjHd4V40vwc4wIYyp89xhm4dSAQd8MVADSRFPoD
    YW61FIcUhrJU1ZsCggEBAM9jSSL0Yaml00knJm9WxtsUOVo+oUFqTZ0ZYnPpDYsr
    x+RivLdmXQTXzeIa5AvmIvGGEdxYYm4/8BpZuljn4VJSgWymQITVK425WXYXwyRO
    kzj7McSAWm9ePlDE1dOuvQl3iZDWvqUXyTA2Qm8PoflEBs84aEim06nO/7rowF0W
    ODTsapNCiNWw67NvGLwsliiWR3myWyECVDmvj98PmawwoS5AnoFGIR4A8aA9D3Cw
    2aV8GYfW/oLMgRdnMTvCb4ia4yRRzjE4I+EzXVKJOCitBFILmUEdvY6MGZ0cxWr2
    ARR53MV0PAcHrEaDkHJ+Fd5sPGviJTJVSywDZhfs2y0CggEBAMdNIa0E2UmKbnEB
    jSbiX/Qqh8Sc58oCmAyvDwhqkCKpZH2H6ESkCAzokwu7yPlzJaj9epNg3frSm/9J
    7lNjgRX5om7mHRDVTkx0yMUyH5QL/Qu3MlWek5KL/kGGE2VoAmUkK1ol3msO/wvZ
    Eyu2h0ci1EL4GrIj4uga8xGV1MVrHncUQ7+HH+soJeQy4+j+QzU2p2DxwdfBADOn
    mPuuToab4U8ISidG1Bz7xr/lDmrdZcREcfhl+87gwKU3qSJ0Q5+bDnzAIKOAGS1K
    WllZeBbTZMayEGKiLSXCQGXmjpWd0H9Fmw9CIg19DyrjTj/JCPaS1n7kOJhknHP1
    NkzcKJsCggEAJsvIDsXwzy+6SuEMC6AMK0epQvycZgRg6JarGEvswLA8ALmH3DdG
    B3XnifjF2IQA3XXbOYE/SKilXgiTF7apLCFLHOws/axzLVwTJEhltREN8YbsVHo+
    cL8MoUdxSNxTeMXn8jR6DaBZfq9n1ibyghL7wyAmQhETX5zdsjWAZumVMjFX7pxv
    xKoILdUGp40fuhAC5v06lv48i14QaAYfFVszi9eCz2QzJc2/Zd6GWOp8jLyeeg76
    JbXkIGCpkShafQ+cllrHW+XIsIRPXPVWkCVtvXt1+/x4TYZf9EhBljTXFuGFL1sD
    L717uOU7zG9R3/4Xf4catkPGgEFSg/9HMQKCAQA+nOGRnAZgSWYqmCyUTZMb9vpA
    wzNAaWFZzbx4QtpHV7HAziTpTHqHe0d5a4U8qxHIWNVpwPlPbxqwevog3iejqF+T
    CM0Og02HWU79MSN0BdWHCXenC5yC2toxv6F60r7hLe2dHnwEbR/Woic58hWbjCls
    b9BIDi/j6wZcuZZHPNJIKi06jqu5Q3F0gzy+VOULwpavzcwskQn7iGq3LA3M7h/n
    lJ7UU8fau2q+daooFSNhZFxZX7+hjtGIvQvSgRJT8gOSBefz5uIIiduNFhGR1TNv
    F7CIxriCbcFErNxOgPrw7qiTQ0gxSL4xEgZtAXpBfrdobjUXawPfi/sRgGyb
    -----END RSA PRIVATE KEY-----


database:
  databaseName: dsw
  authEnabled: true
  username: postgres
  password: postgres
  connectionString: postgresql://postgres:postgres@postgres:5432/dsw

s3:
  url: http://minio:9000
  username: minio
  password: minioPassword
  bucket: dsw

mail:
  enabled: false
  name:
  email:
  host:
  port:
  ssl:
  username:
  password:

cloud:
  enabled: false
  domain: example.com
  publicRegistrationEnabled: true

plan:
  recomputeJob:
    enabled: false
    cron: '* * * * *'
