name: DSW E2E Tests

on:
  push:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      server_image:
        description: 'Wizard Server image'
        required: false
        default: 'dswbot/wizard-server:develop'
      client_image:
        description: 'Wizard Client image'
        required: false
        default: 'dswbot/wizard-client:develop'
      docworker_image:
        description: 'Document Worker image'
        required: false
        default: 'dswbot/document-worker:develop'
        
jobs:
  dsw-e2e:
    name: Run DSW E2E Tests
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]

    steps:
    - uses: actions/checkout@v4

    - name: Set variables from repository dispatch
      if: github.event_name == 'repository_dispatch'
      uses: allenevans/set-env@v3.0.0
      with:
        SERVER_IMAGE: ${{ github.event.client_payload.server_image }}
        CLIENT_IMAGE: ${{ github.event.client_payload.client_image }}
        DOCWORKER_IMAGE: ${{ github.event.client_payload.docworker_image }}

    - name: Set variables from workflow dispatch
      if: github.event_name == 'workflow_dispatch'
      uses: allenevans/set-env@v3.0.0
      with:
        SERVER_IMAGE: ${{ github.event.inputs.server_image }}
        CLIENT_IMAGE: ${{ github.event.inputs.client_image }}
        DOCWORKER_IMAGE: ${{ github.event.inputs.docworker_image }}

    - name: Prepare
      run: |
        docker login -u "$PRIVATE_REGISTRY_USERNAME" -p "$PRIVATE_REGISTRY_PASSWORD" "$PRIVATE_REGISTRY_URL"
        make clean
        make init
      env:
        PRIVATE_REGISTRY_URL: ${{ secrets.PRIVATE_REGISTRY_URL }}
        PRIVATE_REGISTRY_USERNAME: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
        PRIVATE_REGISTRY_PASSWORD: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

    - name: Start DS Wizard
      run: |
        make start
        make wait

    - name: Run Cypress
      uses: cypress-io/github-action@v6
      if: env.CYPRESS_RECORD_KEY != ''
      with:
        browser: chrome
        headed: false
        record: true
        parallel: true
        group: 'DSW E2E Test @ GitHub Actions'
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Cypress (no record)
      uses: cypress-io/github-action@v6
      if: env.CYPRESS_RECORD_KEY == ''
      with:
        browser: chrome
        headed: false
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
